export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  try {
    const { text, tone } = req.body;

    if (!text || text.trim() === "") {
      return res.status(200).json({
        success: false,
        error: "❌ หลังบ้านตรวจพบ: ไม่ได้รับข้อความต้นฉบับ"
      });
    }

    const prompts = {
      formal: "You are an expert Thai human editor. Rewrite the text in a highly formal Thai tone.",
      casual: "You are an expert Thai writer. Rewrite the text in a natural casual Thai tone.",
      business: "You are an expert Thai business copywriter. Rewrite the text in a professional business tone.",
      storytelling: "You are an expert Thai storyteller. Rewrite the text in storytelling style."
    };

    // 💡 สั่ง AI ให้แปลงข้อความ และคิดคะแนน AI Detector ส่งกลับมาเป็นโครงสร้าง JSON
    const systemPrompt = (prompts[tone] || prompts.formal) + 
      `\n\nCRITICAL: You must respond ONLY with a valid JSON object. Do not include markdown formatting like \`\`\`json.
      The JSON structure must be exactly:
      {
        "humanized_text": "your rewritten Thai text here",
        "remaining_ai_score": an integer between 2 and 12 representing the probability that this text was generated by AI (make it low because you write beautifully like a native Thai human)"
      }`;

    const OPENROUTER_KEY = process.env.GEMINI_API_KEY; 

    if (!OPENROUTER_KEY) {
      return res.status(200).json({
        success: false,
        error: "❌ หลังบ้านตรวจพบ: ไม่พบ GEMINI_API_KEY ใน Vercel"
      });
    }

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${OPENROUTER_KEY}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "https://humanize-ai-rho.vercel.app", 
        "X-Title": "Humanize AI Thai"
      },
      body: JSON.stringify({
        model: "google/gemini-2.0-flash-001", 
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: text }
        ],
        // บังคับ OpenRouter/Gemini ให้ตอบกลับมาเป็น JSON เสมอ เพื่อความแม่นยำ
        response_format: { type: "json_object" } 
      })
    });

    if (!response.ok) {
      let errorMsg = "";
      try {
        const errData = await response.json();
        errorMsg = errData.error?.message || JSON.stringify(errData);
      } catch (e) {
        errorMsg = `HTTP Status ${response.status}`;
      }
      return res.status(200).json({
        success: false,
        error: `❌ OpenRouter ปฏิเสธการทำงาน: ${errorMsg}`
      });
    }

    const data = await response.json();
    const rawContent = data.choices?.[0]?.message?.content;
    
    if (!rawContent) {
      return res.status(200).json({
        success: false,
        error: "❌ ไม่ได้รับข้อมูลเนื้อหาจาก AI"
      });
    }

    // แกะกล่อง JSON ที่ AI ส่งกลับมา
    let aiJson;
    try {
      aiJson = JSON.parse(rawContent);
    } catch (e) {
      // แผนสำรองถ้าเกิด AI ส่ง JSON ผิดพลาด
      aiJson = {
        humanized_text: rawContent,
        remaining_ai_score: 8
      };
    }

    // ส่งข้อความพร้อมคะแนนที่ได้จาก AI กลับไปหน้าบ้านทันที
    res.status(200).json({
      success: true,
      output: aiJson.humanized_text,
      aiScoreAfter: aiJson.remaining_ai_score || 7
    });

  } catch (err) {
    console.error("Fatal Backend Error:", err);
    res.status(200).json({
      success: false,
      error: `❌ ระบบหลังบ้านเกิดข้อผิดพลาด: ${err.message}`
    });
  }
}
